Repository arfc/osier, pull requests merged in 2024-09, with the labels that each got.

#65 Updates installer issues and resolves the pyomo logging error
  .github/workflows/CI.yml
  .readthedocs.yaml
  README.md
  osier/models/capacity_expansion.py
  osier/models/dispatch.py
  pyproject.toml
  setup.py
  tests/test_equations.py
  tests/test_models.py
Labels: Comp:Build, Difficulty:2-Challenging, Priority:1-Critical, Status:5-In Review, Type:Bug, Type:Docs, Type:Feature

#68 adds coverage and failunder to pytest command
  pyproject.toml
Labels: Comp:Build, Difficulty:1-Beginner, Priority:2-Normal, Status:5-In Review, Type:Test

#66 Joss paper update.
  .github/workflows/draft-pdf.yml
  paper/paper.bib
  paper/paper.md
Labels: Comp:Output, Difficulty:1-Beginner, Priority:1-Critical, Status:5-In Review, Type:Docs
